---
title: "Data Group Project"
author: "Victoire Truchon-Bartès & Emmanuel de MOREL"
format: html
---

Here the link to the github project : https://github.com/EmmDM/M1_QE_data_group_project

<<<<<<< HEAD
Here the links to the original sources : For the OECD : https://data-explorer.oecd.org/vis?lc=fr&pg=0&fs\[0\]=Th%C3%A8me%2C1%7CEnvironnement%23ENV%23%7CPolitiques%20de%27l%20environnementale%23ENV_POL%23&bp=true&snb=8&df\[ds\]=dsDisseminateFinalDMZ&df\[id\]=DSD_GG%40DF_GREEN_GROWTH&df\[ag\]=OECD.ENV.EPI&df\[vs\]=1.0&pd=1990%2C2022&dq=FRA.A.CO2_PBPROD%2BCO2_PBEMCAP%2BCO2_PBEM%2BCO2_DBPROD%2BCO2_DBPROD_NNDI%2BCO2_DBEMCAP%2BCO2_DBEM%2BNRG_PROD%2BNRG_INT%2BNRGS%2BRE_TPES%2BRE_NRG%2BNRGC%2BRE_TPES_EBIOM%2BMWAS_INT%2BMWAS_INC%2BMWAS_RECO%2BMWAS_LANDF%2BEAMFP_EAMFPG%2BEAMFP_NKG%2BWATER_STPC%2BWATER_FWCAP%2BWATER_FW%2BPM_PWM%2BPM_SPEX10%2BPM_SPEX35%2BPM_MOR%2BPM_SC%2BDRIN_SPOP%2BSANI_SPOP%2BHD_POP_IND%2BRF_POP_IND%2BFT_POP_IND%2BID_POP_IND%2BGPAT_DE%2BENVRD_GBAORD%2BRERD_ERD%2BERD_GDP%2BFFRD_ERD%2BEPEA_GDP%2BODA_ENV%2BODA_BIO%2BODA_CCMIT%2BODA_CCADP%2BODA_DES%2BODA_RE%2BODA_ENVSEC%2BODA_GNI%2BENVTAX%2BENGTAX%2BENVTAX_VEH%2BECR_PC30UP%2BECR_PC60UP%2BECR_PC120UP%2BFTAX_DIE%2BFPRICE_DIE%2BFTAX_PET%2BFPRICE_PET%2BEPRICE_RES%2BEPRICE_IND%2BCSE%2BPSE_FFS%2BGSSE_FFS%2BPET_FFS%2BCOAL_FFS%2BNATG_FFS%2BELEC_FFS%2BFFS_TTAX%2BPA_MARINE%2BPA_TERRESTRIAL%2BGDP_R%2BGDP_PC%2BGDP_RCAP%2BXR%2BDEF%2BPOP_F%2BPOP_Y_LT14%2BPOP_Y15T64%2BPOP_Y_GT65%2BPOP_FERTILITY%2BPOP_LIFEEXP%2BPOP_NETMIGR%2BPOPDEN%2BPPP..&to\[TIME_PERIOD\]=false&ly\[rw\]=MEASURE%2CUNIT_MEASURE&ly\[cl\]=TIME_PERIOD&ly\[rs\]=ACTIVITY&vw=tb

And for the World Bank : https://donnees.banquemondiale.org/theme/changement-climatique

=======
Here the links to the original sources : 
For the OECD : 
https://stats.oecd.org/index.aspx?lang=fr&datasetcode=green_growth

And for the World Bank : https://donnees.banquemondiale.org/theme/changement-climatique

```{r}
#Description des sources
```


```{r}
#Description de la question de recherche
```

```{r}
#Séléction des librairies
library(here)
library(dplyr)
library(tidyr)
library(knitr)
library(ggplot2)
library(readr)
library(stringr)
library(readxl)
```

<<<<<<< HEAD
Nous avons ici modifié la base de donnée de la World Bank afin de garder les critères interessants pour notre problématique.

```{r}
# Spécifier le chemin du fichier Excel
chemin <- "C:/Users/Victoire/Documents/Data Base Group project - World bank.xls"
# Lire les données à partir du fichier Excel
donnees <- read_excel(chemin)

```


```{r}
here :: i_am("M1_QE_data_group_project.Rproj")
OCDE_GG <-read.csv(here("OCDE_GREEN_GROWTH.csv" ), sep = ";")
Worldbank <- read_xls("Worldbank.xls")

#Nettoyage base de données OCDE

OCDE_GG <- OCDE_GG %>% select(-`YEA`,-`PowerCode.Code`, -`Reference.Period.Code`,-`Reference.Period`, -`Unit.Code`)
OCDE_GG <- OCDE_GG %>% pivot_wider(names_from= `Année`, values_from =  `Value`)
OCDE_GG <- OCDE_GG %>% select(-`2021`, -`2022`) #On supprime les données 2021 et 2022 car il y a un manque de données

#Nettoyage base de données World Bank

Worldbank <- Worldbank %>% select(-`1960`,-`1961`,-`1962`,-`1963`,-`1964`,-`1965`,-`1966`,-`1967`,-`1968`,-`1969`,-`1970`,-`1971`,-`1972`,-`1973`,-`1974`,-`1975`,-`1976`,-`1977`,-`1978`,-`1979`,-`1980`,-`1981`,-`1982`,-`1983`,-`1984`,-`1985`,-`1986`,-`1987`,-`1988`,-`1989`,-`2021`, -`2022`) #On conserve seulement période de 1990 à 2020 afin de faire des comparaisons avec les données de l'OCDE. On supprime les données 2021 et 2022 car il y a un manque de données

```
```{r}
# Un tableau par fichier de données qui donne des informations basiques sur ce fichier, en incluant le nombre de lignes et de colonnes (description of Raw data file or clean data file ?)
```


```{r}
# Description du data cleaning et du data joining
```

>>>>>>> 0941e0ec656b0f031354ee4303f649d57021e6a


```{r} 
# Tri des variables base de données OCDE 


Variables_to_select <- c(
  "Productivité CO2 induite par la production, PIB par unité d'émission de CO2 liée à l'énergie",
  "Intensité CO2 induite par la production, émissions de CO2 liées à l'énergie, par habitant",
  "Émissions de CO2 induites par la production",
  "Intensité énergétique, ATE par habitant",
  "Energies renouvalabes,% approvisionnement total en énergie",
  "Electricité renouvelable, % de la production électrique totale",
  "Exposition moyenne de la population aux PM2.5",
  "Pourcentage de la population exposée à plus de 10 microgrammes/m3",
  "Développement de technologies liées à l'environnement, % inventions dans le monde",
  "Développement de technologies liées à l'environnement, inventions par habitant",
  "Recettes provenant des taxes liées à l'énergie, % recettes des taxes environnementales",
  "Soutien aux consommateurs de combustibles fossiles, % recettes totales des taxes",
  "Soutien au pétrole, % soutien total aux combustibles fossiles",
  "Soutien à l'électricité, % soutien total aux combustibles fossiles",
  "Soutien total aux combustibles fossiles, % recettes totales des taxes",
  "Zone marine protégée, % zone économique exclusive totale",
  "Zone terrestre protégée, % surface terrestre",
  "PIB réel",
  "PIB réel par habitant",
  "Migration nette",
  "Consommation d'énergie par l'industrie, % consommation totale d'énergie",
  "Consommation d'énergie par l'agriculture, % consommation totale d'énergie",
  "Consommation d'énergie par les autres secteurs, % consommation totale d'énergie",
  "Productivité énergétique, PIB par unité d'ATE",
  "PIB par unité d'ATE",
  "Approvisionnements totaux en énergie",
  "Prélèvements bruts d'eau douce par habitant",
  "Stress hydrique, total des prélèvements d'eau douce en % des ressources internes renouvelables",
  "Pourcentage de la population exposée à plus de 35 microgrammes/m3",
  "Mortalité due à l'exposition aux PM2.5",
  "Coûts en bien-être dus à l'exposition aux PM2.5, PIB équivalent",
  "Pourcentage de la population exposée aux journées chaudes",
  "Pourcentage de la population exposée aux journées glacées",
  "Pourcentage de la population exposée aux inondations fluviales"
)

OCDE_data_filtere <- OCDE_GG %>%
  filter(Variable %in% Variables_to_select)


# Description des variables séléctionnées OCDE

# "Productivité CO2 induite par la production": Mesure de l'efficacité dans la réduction des émissions de CO2 pendant les processus de fabrication.
# 
# "PIB par unité d'émission de CO2 liée à l'énergie": Évaluation de la performance économique relative à l'émission de CO2 associée à la production d'énergie.
# 
# "Intensité CO2 induite par la production, émissions de CO2 liées à l'énergie, par habitant": Indicateur de la quantité de CO2 émise par habitant due à la production et à la consommation d'énergie.
# 
# "Émissions de CO2 induites par la production": Mesure totale des gaz à effet de serre générés lors des processus de production.
# 
# "Intensité énergétique, ATE par habitant": Évaluation de la consommation énergétique par habitant, ajustée en fonction de l'efficacité énergétique.
# 
# "Approvisionnement total en énergie en énergies renouvelables": Quantité globale d'énergie provenant de sources renouvelables.
# 
# "Production électrique totale en énergies renouvelables": Évaluation de la production d'électricité issue de sources d'énergie renouvelables.
# 
# "Exposition moyenne de la population aux PM2.5": Niveau moyen d'exposition de la population aux particules fines PM2.5.
# 
# "Pourcentage de la population exposée à plus de 10 microgrammes/m3": Proportion de la population confrontée à des niveaux élevés de PM2.5.
# 
# "Technologie et innovation: Brevets": Nombre de brevets déposés, reflétant l'activité innovante et technologique.
# 
# "Recettes provenant des taxes liées à l'environnement": Montant des revenus générés par les taxes environnementales.
# 
# "Soutien aux consommateurs de combustibles fossiles": Indicateur des subventions allouées aux consommateurs de combustibles fossiles.
# 
# "Soutien au pétrole": Montant des subventions spécifiquement attribuées au secteur pétrolier.
# 
# "Soutien à l'électricité": Niveau de soutien financier accordé au secteur de l'électricité.
# 
# "Soutien total aux combustibles fossiles": Somme des subventions allouées aux consommateurs et producteurs de combustibles fossiles.
# 
# "Zone marine protégée": Étendue océanique légalement préservée pour la conservation de la biodiversité.
# 
# "Zone terrestre protégée": Surface terrestre réservée légalement à la protection de la faune et de la flore.
# 
# "PIB réel": Mesure ajustée de la production économique, tenant compte de l'inflation.
# 
# "PIB réel par habitant": PIB réel divisé par la population, indiquant le niveau de vie moyen.
# 
# "Migration nette": Différence entre le nombre d'immigrants et d'émigrants, influençant la croissance démographique.
# 
# "Consommation d'énergie": Quantité totale d'énergie consommée dans une économie.
# 
# "Émissions de CO2 induites par la production": Mesure des émissions de CO2 attribuables aux activités de production.
# 
# "Productivité énergétique": Efficacité dans l'utilisation de l'énergie pour la production économique.
# 
# "PIB par unité d'ATE": Évaluation de la productivité économique par unité d'ATE (énergie ajustée au travail).
# 
# "Approvisionnements totaux en énergie": Total de l'énergie disponible pour une économie.
# 
# "Prélèvements bruts d'eau douce par habitant": Quantité totale d'eau douce prélevée par habitant.
# 
# "Stress hydrique, total des prélèvements d'eau douce": Mesure de la pression exercée sur les ressources hydriques en raison des prélèvements totaux d'eau douce.
# 
# "Pourcentage de la population exposée à plus de 35 microgrammes/m3": Proportion de la population confrontée à des niveaux élevés de PM2.5.
# 
# "Mortalité due à l'exposition aux PM2.5": Nombre de décès attribués à l'exposition aux particules fines PM2.5.
# 
# "Coûts en bien-être dus à l'exposition aux PM2.5": Évaluation des impacts économiques négatifs liés à la santé dus à l'exposition aux PM2.5.
# 
# "PIB équivalent": Mesure agrégée du bien-être économique, prenant en compte des facteurs tels que l'environnement et la santé.
# 
# "Pourcentage de la population exposée aux journées chaudes": Proportion de la population subissant des températures élevées.
# 
# "Pourcentage de la population exposée aux inondations fluviales": Part de la population résidant dans des zones exposées aux inondations fluviales.


# Tri des variables base de données World bank


# Define the variables to select
indicators_to_select <- c(
  "Population urbaine (% du total)",
  "Population urbaine",
  "Croissance de la population urbaine (% annuel)",
  "Population, total",
  "Croissance de la population (% annuel)",
  "Agriculture, valeur ajoutée (% du PIB)",
  "Zones terrestres et marines protégées (% du territoire total)",
  "Zones marines protégées (% des eaux du territoire)",
  "Émissions/éliminations nettes de GES attribuables au changement d'affectation des terres et à la foresterie (Mt d’équivalents CO2)",
  "Note sur les progrès de réduction des risques de catastrophes (échelle de 1 à 5, 5 étant la meilleure note)",
  "Émissions totales de GES (variation depuis 1990, %)",
  "Émissions totales de GES (kt d’équivalent CO2)",
  "Zones protégées à l'échelle nationale (% du territoire total)",
  "Retraits annuels d’eau douce, total (% des ressources internes)",
  "Retraits annuels d’eau douce, total (milliards de mètres cubes)",
  "Autres émissions de gaz à effet de serre, HFC, PFC et SF6 (milliers de tonnes métriques d’équivalent CO2)",
  "Émissions de CO2 (tonnes métriques par habitant)",
  "Sécheresses, inondations, températures extrêmes (en % de la population, moyenne de 1990 à 2009)",
  "Émissions de CO2 (kg par $ US de 2010 de PIB)",
  "Intensité en CO2 (kg par kg d’utilisation d’énergie en équivalent pétrole)",
  "Utilisation d’énergie (kg d’équivalent pétrole par habitant)",
  "Consommation d’électricité (KWh par habitant)",
  "Utilisation d’énergie (en kg d’équivalent pétrole) pour 1 000 $ de PIB (PPA constants de 2011)",
  "Consommation d’énergies renouvelables (% de la consommation totale d’énergie)",
  "Production d’électricité à partir de sources d’énergie renouvelables, hors énergie hydroélectrique (% du total)",
  "Production d’électricité à partir de sources d’énergie renouvelables, hors énergie hydroélectrique (kWh)",
  "Accès à l’électricité (% de la population)",
  "Hauteur moyenne des précipitations (mm par an)",
  "Terres agricoles (km carrés)",
  "Émissions de CO2 (kg par $ PPA de 2011 de PIB)",
  "Émissions de CO2 (kt)",
  "Production d’électricité renouvelable (% de la production totale d’électricité)",
  "Production d’électricité à partir de sources pétrolières (% du total)",
  "Production d’électricité à partir de sources nucléaires (% du total)",
  "Production d’électricité à partir de sources de gaz naturel (% du total)",
  "Production d’électricité à partir de sources hydroélectriques (% du total)",
  "Production d’électricité à partir de sources de charbon (% du total)",
  "Surface forestière (% du territoire)",
  "Terres agricoles (% du territoire)"
)

# Filter the worldbank dataset
worldbank_filtered <- Worldbank %>%
  filter(`Indicator Name` %in% indicators_to_select)


```

```{r}
# Description des variables séléctionnées Worldbank

# "Population urbaine (% du total)": Pourcentage de la population résidant en milieu urbain par rapport à la population totale.
# 
# "Population urbaine": Nombre total d'habitants vivant en milieu urbain.
# 
# "Croissance de la population urbaine (% annuel)": Taux de croissance annuel de la population urbaine.
# 
# "Population, total": Nombre total d'habitants, incluant les zones urbaines et rurales.
# 
# "Croissance de la population (% annuel)": Taux de croissance annuel de la population totale.
# 
# "Agriculture, valeur ajoutée (% du PIB)": Contribution de la valeur ajoutée de l'agriculture au produit intérieur brut (PIB).
# 
# "Zones terrestres et marines protégées (% du territoire total)": Pourcentage du territoire total réservé aux zones terrestres et marines protégées.
# 
# "Zones marines protégées (% des eaux du territoire)": Proportion des eaux territoriales réservée aux zones marines protégées.
# 
# "Émissions/éliminations nettes de GES attribuables au changement d'affectation des terres et à la foresterie (Mt d’équivalents CO2)": Quantité nette d'émissions ou de séquestration de gaz à effet de serre résultant des changements dans l'utilisation des terres et de la foresterie.
# 
# "Note sur les progrès de réduction des risques de catastrophes (échelle de 1 à 5, 5 étant la meilleure note)": Évaluation des progrès dans la réduction des risques de catastrophes naturelles sur une échelle de 1 à 5.
# 
# "Émissions totales de GES (variation depuis 1990, %)": Variation en pourcentage des émissions totales de gaz à effet de serre depuis 1990.
# 
# "Émissions totales de GES (kt d’équivalent CO2)": Total des émissions de gaz à effet de serre mesurées en milliers de tonnes d'équivalents CO2.
# 
# "Zones protégées à l'échelle nationale (% du territoire total)": Pourcentage du territoire national réservé à des zones protégées.
# 
# "Retraits annuels d’eau douce, total (% des ressources internes)": Pourcentage des ressources internes utilisé par les retraits annuels d'eau douce.
# 
# "Retraits annuels d’eau douce, total (milliards de mètres cubes)": Volume total des retraits annuels d'eau douce mesuré en milliards de mètres cubes.
# 
# "Autres émissions de gaz à effet de serre, HFC, PFC et SF6 (milliers de tonnes métriques d’équivalent CO2)": Émissions de gaz à effet de serre autres que le dioxyde de carbone, mesurées en milliers de tonnes métriques d'équivalent CO2.
# 
# "Émissions de CO2 (tonnes métriques par habitant)": Quantité de CO2 émise par habitant, mesurée en tonnes métriques.
# 
# "Sécheresses, inondations, températures extrêmes (en % de la population, moyenne de 1990 à 2009)": Pourcentage moyen de la population exposée à des événements climatiques extrêmes entre 1990 et 2009.
# 
# "Émissions de CO2 (kg par $ US de 2010 de PIB)": Intensité des émissions de CO2 par unité de PIB, mesurée en kilogrammes par dollar américain de 2010.
# 
# "Intensité en CO2 (kg par kg d’utilisation d’énergie en équivalent pétrole)": Mesure de l'intensité des émissions de CO2 par unité d'utilisation d'énergie, convertie en équivalent pétrole.
# 
# "Utilisation d’énergie (kg d’équivalent pétrole par habitant)": Quantité d'énergie utilisée par habitant, mesurée en kilogrammes d'équivalent pétrole.
# 
# "Consommation d’électricité (KWh par habitant)": Quantité d'électricité consommée par habitant, mesurée en kilowattheures.
# 
# "Utilisation d’énergie (en kg d’équivalent pétrole) pour 1 000 $ de PIB (PPA constants de 2011)": Consommation d'énergie par unité de PIB, ajustée en parité de pouvoir d'achat constante de 2011.
# 
# "Consommation d’énergies renouvelables (% de la consommation totale d’énergie)": Pourcentage de la consommation totale d'énergie provenant de sources renouvelables.
# 
# "Production d’électricité à partir de sources d’énergie renouvelables, hors énergie hydroélectrique (% du total)": Pourcentage de la production totale d'électricité provenant de sources d'énergie renouvelables, excluant l'hydroélectricité.
# 
# "Production d’électricité à partir de sources d’énergie renouvelables, hors énergie hydroélectrique (kWh)": Quantité d'électricité produite à partir de sources d'énergie renouvelables, excluant l'hydroélectricité, mesurée en kilowattheures.
# 
# "Accès à l’électricité (% de la population)": Pourcentage de la population ayant accès à l'électricité.
# 
# "Hauteur moyenne des précipitations (mm par an)": Moyenne annuelle de la hauteur des précipitations mesurée en millimètres.
# 
# "Terres agricoles (km carrés)": Surface totale utilisée pour l'agriculture, mesurée en kilomètres carrés.
# 
# "Émissions de CO2 (kg par $ PPA de 2011 de PIB)": Intensité des émissions de CO2 par unité de PIB, ajustée en parité de pouvoir d'achat constante de 2011 et mesurée en kilogrammes par dollar.
# 
# "Émissions de CO2 (kt)": Total des émissions de CO2 mesuré en milliers de tonnes.
# 
# "Production d’électricité renouvelable (% de la production totale d’électricité)": Pourcentage de la production totale d'électricité provenant de sources d'énergie renouvelables.
# 
# "Production d’électricité à partir de sources pétrolières (% du total)": Pourcentage de la production totale d'électricité provenant de sources pétrolières.
# 
# "Production d’électricité à partir de sources nucléaires (% du total)": Pourcentage de la production totale d'électricité provenant de sources nucléaires.
# 
# "Production d’électricité à partir de sources de gaz naturel (% du total)": Pourcentage de la production totale d'électricité provenant de sources de gaz naturel.
# 
# "Production d’électricité à partir de sources hydroélectriques (% du total)": Proportion de la production totale d'électricité générée à partir de sources hydroélectriques.
# 
# "Production d’électricité à partir de sources de charbon (% du total)": Pourcentage de la production totale d'électricité provenant de sources de charbon.
# 
# "Surface forestière (% du territoire)": Pourcentage du territoire couvert par des surfaces forestières.
# 
# "Terres agricoles (% du territoire)": Proportion du territoire utilisée à des fins agricoles.

```

```{r}
#Tri des pays base de données OCDE

#Tri des pays base de données World bank
```

```{r}
# Description du data cleaning et du data joining
```
``
```{r}
# Description des sources 
 ## OCDE : La base de donnée provient de l'Organisation de coopération et de développement économique,crée en 1961, qui regroupe 38 pays membres. Elle leur permet de pouvoir partager des données, des analyses et des recommandation visant a améliorer les performances dans diverses domaines.Son but étant de favoriser la croissance économique inclusive et le progrès durable. Elle travaille en collaboration avec les pouvoirs publics, les acteurs économiques et sociaux, et les representants de la sociétée civile.Cette plateforme que nous avons choisis pour notre première base de donnée, est choisis par de nombreux dirigeants grâce à sa qualité et sa fiabilité. L'accès à des données sur lesquel nous pouvons nous aider, offrent des perspectives approfondies sur les défis mondiaux et facilite les prises de décisions.Ces données proviennent de ses pays membres qui partagent des normes communes en matières de collecte de donnée, facilitant ainsi la comptabilité de celles-ci.Elle réalise aussi des analyses appronfondies sur de nombreux sujets économiques, sociaux et environnementaux et publie des rapports, des études et des statistiques qui sont regulièrement mis à jourpour refléter l'évolution des tendances des pays membres. 


## Worldbank : La Banque Mondiale est une Institution financière internationale ,crée en 1944, qui a financé plus de 12000 projets de développement. Elle offre des services de financements, d'expertise et de recherche afin de soutenir le developpement économique, et la reduction de la pauvreté. Elle se compose de 5 Institutions dont les deux plus importantes sont la Banque internationale pour la reconstruction et le développement (BIRD) et l'Association internationale de développement (IDA). Elle collabore avec les pays membres, les ONG, le secteur privé, et d'autres partenaires. En plus de sa mission de financement, la Banque mondiale collecte et publie des donnés. Sa base apellé World Development Indicators (WDI) contient des informations sur les pays du monde entiers couvrants des sujets tels que la croissance économique, la pauvreté, l'éducation ..etc A l'image de l'OCDE, cette mine d'information est utilisé par de nombreux dirigeants ainsi que des chercheurs afin de d'informer les prises de décisions en matière de développement assuré par des normes rigoureuses de collecte. Ses données sont également régulièrement mises à jour afin de réfleter les évolutions des pays concernés. 




```

```{r}
#Question de Recherche 

# ## La conference de Rio+20 qui a eu lieu en 2012, a été un véritable lancement pour le développement durable. En effet c'est lors de cet evenement que les objectifs de  décarbonisation et de croissance verte ont été decidé. Ce sujet nous paraît important au vu de l'impact de l'activité humaine sur l'environnement, et d'autant plus en 2023 afin de faire des constats mais aussi de voir les évolutions des solutions envisagées voir deja mise en place. 
# 
# Notre Projet de recherche sera portée sur l'Analyse des tendances de transition écologique: une étude comparative des pays au sein et en dehors de l'OCDE entre 1990 et 2022. 
# 
# ###Nous aurons 3 grands axes de recherches: Le découplage de la croissance, les différentes polices mises en place et la Vulnérabilité grandissante de nos sociétés face aux urgences climatiques. 
# 
# Le terme découplage est habituellement utilisé pour désigner la possibilité d'une croissance économique, mesuré par une hausse du PIB, qui a lieu de manière simultanée à une baisse des consommations de ressources et des impacts environnementaux. 
# Dans cette partie, nous allons mesurer le PIB et en voir sa composition en terme d'energie utilisé. Les énergies polluantes étant les moins coûteuses et plus génératrice de revenue, elles sont souvent la composante principale. L'efficacité de l'utilisation des ressources et la productivité du carbone seront également scrutées, en se concentrant sur des indicateurs tels que le PIB par unité d'émission de CO2. 
# 
# Dans un second temps, nous étudierons les pressions environnementales, analysant les tendances liées à l'intensité énergétique, à la qualité de l'air, et à l'adoption de source d'énergie renouvelable. Cette partie se penchera aussi sur les polices mises en place (taxes, subventions), et les efforts en R&D afin de favoriser la transition écologique. Elles nous permettrons également d'observer le lien de corrélation entre les mesures politiques et les résultats écologiques. 
# 
# 
# Dans un dernier temps, nous évaluerons la vulnérabilité des pays aux événements liés au réchauffement climatique, tels que les inondations, les incendies et les températures extrêmes. Nous examinerons également le rôle des facteurs géographiques et démographiques dans l'influence de cette vulnérabilité. Les schémas de migrations de populations seront également examinés en tant que potentielles stratégies d'adaptation aux changements environnementaux. 
# 
# En conclusion, notre recherche ambitionne de fournir des perspectives sur les dynamiques de la transition écologiques , en comparant différents groupes de pays intérieur ou extérieur à l'OCDE. Nous appuierons notre démarche sur des représentations graphiques à l'aide de subplot, graphe divers, et d'autres utilisations de donnée à l'aide de R. 
# ```


```{r}

```

